name: Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: python -m pip install --upgrade setuptools "Cython~=3.0" pytest
      - name: Build source distribution
        run: python setup.py sdist --cythonize
      - name: Install source distribution
        run: python -m pip install dist/pe-*.tar.gz
      - name: Test source distribution
        run: pytest test/
      - name: Store the source distribution
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz
          retention-days: 4

  build-wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.17.0
        env:
          CIBW_SKIP: "pp* *-win32 *linux_i686"  # skip PyPy, 32-bit
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/test/"
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
      - build-sdist
      - build-wheels
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pe
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4.1.7
        with:
          name: dist
          path: dist/
      - name: To be published
        run: ls -l dist
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
