# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      run: |
        python -m pip install --upgrade pip cython
        cythonize -3i pe/*.pyx
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 pe --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. PEP-8 says 99 chars is a good width
        flake8 pe --count --exit-zero --max-complexity=10 --max-line-length=99 --statistics
    - name: Test with pytest including doctests
      if: ${{ matrix.python-version == '3.9' }}
      run: |
        pip install pytest
        pytest --doctest-glob=\*.md
    - name: Test with pytest
      if: ${{ matrix.python-version != '3.9' }}
      run: |
        pip install pytest
        pytest
    - name: Type-check with mypy
      run: |
        pip install mypy
        mypy pe
